name: Test PR
'on': pull_request

jobs:
  install-and-test:
    name: 🛠️ Install & Test
    runs-on: ubuntu-latest

    steps:
      - name: 🗜️ Checkout
        uses: actions/checkout@v4

      - name: 🗜️ Setup node version
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: 🛠️ Install
        uses: ./.github/actions/cached-deps

      - name: 🛠️ Sync versions
        run: yarn script:sync-projects

      - name: 🛠️ Find PR
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: 🧹 Lint
        run: yarn lint

      - name: 🧪 Run tests
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          prnumber: ${{ steps.findPr.outputs.number }}
          test_command: yarn test:jest
          coverage_threshold: 90
          output: comment, report-markdown

      - name: ⬆️ Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
          dry_run: true

      - name: 📦 Build demo app
        run: yarn build:demo --base-href https://celtian.github.io/ngx-repeat/

      - name: 📦 Build ngx-repeat
        run: yarn build
