name: Test PR
'on': pull_request

jobs:
  install-and-test:
    name: 🛠️ Install & Test
    runs-on: ubuntu-latest

    steps:
      - name: 🗜️ Checkout
        uses: actions/checkout@v7

      - name: 🗜️ Setup node version
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: 🛠️ Install
        uses: ./.github/actions/cached-deps

      - name: 🛠️ Sync versions
        run: yarn script:sync-projects

      - name: 🧹 Lint
        run: yarn lint

      - name: ♻️ Check circular dependencies
        run: yarn check-circular-dependencies

      - name: 🧪 Run tests (ngx-repeat)
        run: yarn test ngx-repeat

      - name: 🧪 Run tests (demo)
        run: yarn test demo

      - name: ⬆️ Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
          dry_run: true

      - name: 📦 Build demo app
        run: yarn build:demo --base-href https://celtian.github.io/ngx-repeat/

      - name: 📦 Build ngx-repeat
        run: yarn build
